export default function Home() {
  return (
    <main className="mt-4">
      <div className="mx-auto max-w-3xl xl:max-w-7xl">
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-3">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607067/013_hlbvas_uwdm7y.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607065/08_mvg5h4_edox5f.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606426/00_d8bech_edg38h.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607063/02_uk15hb_fooxnb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607057/06_eviwcm_rmmhku.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607045/03_htugsa_k7fx12.mp4"
            }
          />

          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606426/012_wtq2dx_eqabzu.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606907/01_uperzv_hhld1u.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606992/05_pn5czc_hmb1iy.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607001/010_rjbf0d_n53l03.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606426/04_qyyiwb_emneiu.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606424/09_lpbgv4_gh3qhs.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606422/07_wfyd5k_lpp3wb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606420/016_ehachw_lvfpef.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606416/015_ngtqoj_rvvm01.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606408/014_mfjhge_ls54er.mp4"
            }
          />
        </div>
      </div>
    </main>
  );
}
