export default function Home() {
  return (
    <main className="mt-4">
      <div className="mx-auto max-w-3xl xl:max-w-7xl">
        <div className="pb-2">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1726043923/IDCUBE_Video_2_oii2ve.mp4"
            }
          />
        </div>
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607099/3_likg2t_n4xlwz.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607095/2_kol6av_jhiiee.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607064/4_jpzscs_yn6yq1.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607053/1_axo8ke_gomxnk.mp4"
            }
          />
        </div>
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-3">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607072/060_ltzuhh_tsq6ut.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607043/056_mmonti_umovk4.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725607043/052_tnc6k1_lvk4kt.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606999/09_bzk3q2_qkd6th.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606990/011_h43bab_dy03ed.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606990/02_wrqra7_tw8w8x.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606426/01_biln5v_gawtrg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606425/025_tvpe2h_dvqnke.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606424/08_mmhcn9_hioyhs.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606423/053_vqevwo_azb5ke.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606423/04_t760xh_yrxbwg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606423/051_bmy5ic_jhhu29.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606421/048_u14cdg_coqqjb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606421/013_iowkks_o8vy0h.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606421/014_aebxmd_zzpden.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606420/029_jtj3qj_len22q.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606420/03_r8mbrm_h9u42p.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606419/055_k5jwdq_as2fqq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606419/054_jmj06s_kveomo.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606418/015_na74dz_rckdup.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606418/016_hdkwxl_w0cbzz.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606416/07_f0fbox_nruykj.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606415/058_w5ns29_an4m31.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606413/010_yqyq45_dvzrhp.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606413/057_l2usrw_z6aojq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606411/06_olm3sg_ydzwls.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606411/049_vqauco_hbkdfj.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606409/026_rdserl_gu8r7b.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606408/041_hi0uta_veetzm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606407/034_nva5gk_hcava1.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606406/046_e4v249_ypvczt.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606406/045_j6hil2_zuauh4.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606406/012_cbjygg_d9vsho.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606005/030_bzlr36_pv83bm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606005/028_rnonpv_sfax5m.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606004/042_f0kz2w_cm7wap.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606004/050_i7kdh6_xpwbvs.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606002/037_ytlmfq_vygxo6.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606000/038_ltx4nf_rnkur7.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606000/033_ddqq0y_guqgqg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725606000/043_xgthdf_urgrcq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605999/040_auwy7k_z8ts30.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605999/027_gxphp2_hjf4dq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605964/019_lhuffh_ldxphj.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605976/020_fdcwqq_q8urpm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605984/047_vdi9qs_bdna0w.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605985/036_hef0mm_liuh8i.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605985/039_ztxo2v_buukay.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605989/031_ypddbt_dvqnqe.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605989/031_ypddbt_dvqnqe.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/deelfmnhg/video/upload/v1725605995/059_uiulcl_flbcuf.mp4"
            }
          />
        </div>
      </div>
    </main>
  );
}
